### ISSUE TITLE
Beginning C Programmer Wants To Join (Also a question about TinyCC)

### ISSUE THREAD

**Issue by andytrusso** [C-Chads/C-Chads#3]
Hi, I've recently started trying to learn game development with a combination of books on Python, and fiddling around in C with raylib.

I found TinyGL through the suckless website, and through that found this organization. I think it seems really cool what you're all doing, if the day comes that I'm good enough to do so I'd love to use the SDL2 API you've made to make a game. But for the time being, can I join?

Also, while I'm here, I've noticed that with raylib, for some reason GCC won't compile .c files with raylib.h (it says it can't recognize some of the functions) but TCC will? However this is only on Ubuntu-based distros (I've found this on both Pop OS and Lubuntu) but it doesn't happen on Manjaro. It also happens with both the .deb for TCC and after using your fork of it. Any idea why this could be? I'm assuming figuring it out is waaaay above my skill level. 

EDIT: Changed "...enough to do *to*" to "...enough to do *so*".

**Comment by gek169** [comment]
Of course!
I can also probably help you with that raylib issue. It is most likely that you need to set some compiler flags. It's very likely that you're just missing some libraries on Ubuntu.

I'll invite you to the organization.

**Comment by gek169** [comment]
I feel like I should make a comment about "Beginner"

1) We all start somewhere
2) We're all learning, all the time
3) If anyone ever claims to be a "Master" or "Expert" at C programming, then you shouldn't trust them, because they probably don't know what they're talking about.

If anything, i'd be more interested in someone who believed themselves to be a beginner, because they would be more willing and eager to learn.
Of course you are welcome.

**Comment by andytrusso** [comment]
Thanks! I look forward to learning :)
